### ISSUE TITLE
Hotbar slot doesn't 'unlock' after being damaged while carrying a block

### ISSUE THREAD

**Issue by PJ-Mog** [copygirl/CarryCapacity#13]
When carrying a block, if one takes damage the block is forcefully dropped. The issue is that the hotbar slot that was being used to carry remains 'locked' and always appears empty. Moving an item into that slot, the slot still appears empty. Issue can be corrected in-game by picking up a carryable block with the affected hotbar slot and setting it down without taking damage.

**Comment by copygirl** [comment]
I've been aware of this issue for a long time. It also occurs when attempting to pick up something from a protected area (such as a trader's). I've not bothered fixing directly it because I've been wanting to redo a lot of the implementation from scratch, to support additional features such as picking up entities. Then CarryCapacity was considered for adding to the main game, but this has been a while.
